<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[OVAJ TEST JE PAO]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="531" started-at="2020-06-27T18:04:21 CEST" finished-at="2020-06-27T18:04:22 CEST">
    <groups>
    </groups>
    <test name="Test" duration-ms="531" started-at="2020-06-27T18:04:21 CEST" finished-at="2020-06-27T18:04:22 CEST">
      <class name="saucedemofail.SauceDemoTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:saucedemofail.SauceDemoTest@5bc79255]" name="setUp" is-config="true" duration-ms="7415" started-at="2020-06-27T18:04:14 CEST" finished-at="2020-06-27T18:04:21 CEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="getUrl()[pri:0, instance:saucedemofail.SauceDemoTest@5bc79255]" name="getUrl" duration-ms="18" started-at="2020-06-27T18:04:21 CEST" finished-at="2020-06-27T18:04:21 CEST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Incorrect url expected [https://www.saucedemo.co21m/] but found [https://www.saucedemo.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Incorrect url expected [https://www.saucedemo.co21m/] but found [https://www.saucedemo.com/]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at saucedemofail.SauceDemoTest.getUrl(SauceDemoTest.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[OVAJ TEST JE PAO]]>
            </line>
          </reporter-output>
        </test-method> <!-- getUrl -->
        <test-method status="PASS" signature="getScreenshotOnMetFail(org.testng.ITestResult)[pri:0, instance:saucedemofail.SauceDemoTest@5bc79255]" name="getScreenshotOnMetFail" is-config="true" duration-ms="464" started-at="2020-06-27T18:04:21 CEST" finished-at="2020-06-27T18:04:22 CEST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=getUrl status=FAILURE method=SauceDemoTest.getUrl()[pri:0, instance:saucedemofail.SauceDemoTest@5bc79255] output=OVAJ TEST JE PAO]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getScreenshotOnMetFail -->
      </class> <!-- saucedemofail.SauceDemoTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
